export const DEFAULT_LANGUAGE = 'en';

export const DEFAULT_VIEW = 'month';

export const DEFAULT_STUB_CONFIG = {
  title: 'Family Calendar',
  entities: ['calendar.personal'],
  default_view: 'month',
  first_day_of_week: 0,
  week_days: [0, 1, 2, 3, 4, 5, 6],
  week_start_hour: 0,
  week_end_hour: 23,
  lock_schedule_hours: false,
  hide_the_past: false,
  past_event_mode: 'none',
  disable_swipe_controls: false,
  show_all_events_month: false,
  show_all_details_month: false,
  hide_empty_days: false,
  agenda_compact_events: false,
  shorten_event_times: false,
  time_zone: '',
  display_full_weekday_names: false,
  compact_width: false,
  show_current_time_bar: false,
  show_event_location: false,
  use_short_location: false,
  event_location_font_size: 9,
  background_opacity: 0,
  header_background_opacity: 0,
  event_calendar_friendly_name: false,
  event_title_prefix: 'none',
  combine_style: 'bars',
  combine_background: 'primary',
  event_color_mode: 'classic',
  event_neutral_background: '#F8F3E9',
  event_tint_opacity: 80,
  event_color_bar_width: 18,
  day_badges: [],
  day_badge_layout_week: 'inline',
  hide_calendars: false,
  hide_header: false,
  hide_year: false,
  hide_controls: false,
  hide_navigation_buttons: false,
  hide_add_event_button: false,
  hide_view_selector: false,
  hide_dark_mode_toggle: false,
  show_dashboard_nav_button: false,
  header_dashboard_path: null,
  header_weather_sensor: '',
  calendar_person_entities: {},
  default_hidden_calendars: [],
  color_scheme: 'auto',
  enable_event_management: true,
  event_modal_size: 'medium'
};

export const createDefaultStubConfig = () => ({
  ...DEFAULT_STUB_CONFIG,
  entities: [...DEFAULT_STUB_CONFIG.entities],
  week_days: [...DEFAULT_STUB_CONFIG.week_days],
  day_badges: [...DEFAULT_STUB_CONFIG.day_badges],
  calendar_person_entities: { ...DEFAULT_STUB_CONFIG.calendar_person_entities },
  default_hidden_calendars: [...DEFAULT_STUB_CONFIG.default_hidden_calendars]
});
